Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing

In [1]:
import torch
import numpy as np

In [4]:
data = [[1,2],[3,4]]
np_arr = np.array(data) # create np array from data
torch_arr = torch.tensor(data) # create torch tensor from data
print(np_arr, "\n\n", torch_arr)

[[1 2]
 [3 4]] 

 tensor([[1, 2],
        [3, 4]])


In [5]:
np_to_torch = torch.from_numpy(np_arr) # convert np array to torch tensor
print(np_to_torch)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [6]:
torch_to_np = torch_arr.numpy() # convert torch tensor to np array
print(torch_to_np)

[[1 2]
 [3 4]]


In [8]:
#np.ones((2,3))
#np.ones_like()
t_ones = torch.ones_like(torch_arr) # retains the properties of x_data
print(f"Ones Tensor: \n {t_ones} \n")

t_rand = torch.rand_like(torch_arr, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {t_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7745, 0.1878],
        [0.9283, 0.9573]]) 



In [9]:
shape = (2, 3,) #shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0967, 0.5483, 0.4230],
        [0.3946, 0.9185, 0.3761]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
tensor = torch.rand(3, 4) #Tensor attributes describe their shape, datatype, and the device on which they are stored.

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described @

Tensor Operations: https://pytorch.org/docs/stable/torch.html

In [11]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [15]:
tensor = torch.ones(4, 4) #Standard numpy-like indexing and slicing:
tensor[:,1] = 0
print(tensor, tensor.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) torch.Size([4, 4])


In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # join/concatenate tensors along column
print(t1, t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) torch.Size([4, 12])


In [17]:
t2 = torch.cat([tensor, tensor, tensor], dim=0) # join/concatenate tensors along row
print(t2, t2.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) torch.Size([12, 4])


In [27]:
t3 = torch.stack([tensor], dim=1) # stack tensors along 3 dim --> 4x,4y (2d) => 1x, 4y (2d) X 4 (3d)
print(t3, t3.shape, t3.dim(), "\n\n", t3[0], t3[1], t3[2], t3[3])

tensor([[[1., 0., 1., 1.]],

        [[1., 0., 1., 1.]],

        [[1., 0., 1., 1.]],

        [[1., 0., 1., 1.]]]) torch.Size([4, 1, 4]) 3 

 tensor([[1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.]]) tensor([[1., 0., 1., 1.]])


In [29]:
t4 = torch.stack([tensor], dim=0) # stack tensors along 3 dim --> 4x,4y (2d) => 4x,4y (2d) X 1 (3d)
print(t4, t4.shape, t3.dim(), "\n\n", t4[0]) #no structure change 

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]]) torch.Size([1, 4, 4]) 3 

 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Multiplying tensors

In [30]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Matrix multiplication

In [31]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.

In [32]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
